version: '3.8'

services:
  backend:
    image: docker.io/guicaiyue/ga-web-launcher-backend:latest
    ports:
      - "8760:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  frontend:
    image: docker.io/guicaiyue/ga-web-launcher-frontend:latest
    ports:
      - "8761:80"
    depends_on:
      - backend
    restart: unless-stopped
